project:
  type: hugo
  render:
    - "*.qmd"
    - "!archetypes/"

# greedy matching
# https://quarto.org/docs/projects/quarto-projects.html#render-targets

format:
  hugo-md:
    fig-height: 3
    # fig-width: 4.5
    fig-dpi: 600
    code-fold: false
    # html-math-method: webtex

execute:
  warning: false
  # error: false
  cache: true
  freeze: auto

# biliography: references.bib
