theme: "hugo-PaperMod"
baseURL: "/"
publishDir: "../kleinlennart.github.io" # Build to other repo
languageCode: en-us
title: "@kleinbutsignificant"

paginate: 5
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

# googleAnalytics: UA-123-45

## Can result in weird JSON parsing errors
minify:
    disableXML: true
    # minifyOutput: true


menu:
    main:
        - identifier: about
          name: "About"
          url: /about/
          weight: 1
        - identifier: cv
          name: "CV"
          url: /vitae/
          weight: 2
        - identifier: blog
          name: "Blog"
          url: /archives/
          weight: 3
        - identifier: pubs
          name: "Publications"
          url: /pubs/
          weight: 4
        - identifier: projects
          name: "Projects"
          url: /projects/
          weight: 5
        - identifier: categories
          name: "Topics"
          url: /categories/
          weight: 6
        - identifier: tags
          name: "Tags"
          url: /tags/
          weight: 7
        - identifier: search
          name: "🔍"
          url: /search/
          weight: 8

# For search
outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary
       
params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    title: "@kleinbutsignificant"
    description: "Blog of Lennart Klein about Data Science, Politics and Productivity"
    author: "Lennart Klein"
    # author: ["Me", "You"] # multiple authors
    images: ["<link or path of image for opengraph, twitter-cards>"]

    defaultTheme: auto # dark, light
    disableThemeToggle: true

    ShowReadingTime: false
    ShowShareButtons: false
    disableSpecial1stPost: false
    comments: true
    hidemeta: false
    showtoc: false
    tocopen: false
    ShowPostNavLinks: false
    ShowBreadCrumbs: true 

    assets:
        # disableHLJS: true # to disable highlight.js
        # disableFingerprinting: true
        favicon: "favicon16.png"
        favicon16x16: "favicon16.png"
        favicon32x32: "<link / abs url>"
        apple_touch_icon: "<link / abs url>"
        safari_pinned_tab: "<link / abs url>"

    label:
        text: "@kleinbutsignificant"
        # icon: /apple-touch-icon.png
        iconHeight: 35

    # profile-mode
    profileMode:
        enabled: false # needs to be explicitly set
        title: Lennart Klein
        subtitle: "Writing about Data Science, Politics and Productivity"
        imageUrl: "profile.png"
        imageWidth: 150
        imageHeight: 150
        imageTitle: my image
        buttons:
            - name: Posts
              url: posts
            - name: Tags
              url: tags

    # home-info mode
    homeInfoParams:
        Title: "Hi, I'm Lennart \U0001F44B"
        Content: > 
          - I write about Data Science, Politics and Productivity.
          
          -
        
          - 🧑‍🎓Undergraduate Student of Political Science, Sociology and Psychology
          
          - at [University of Tübingen](https://uni-tuebingen.de/en/).
          
          - Research Assistant at [Hector Research Institute](https://uni-tuebingen.de/en/faculties/faculty-of-economics-and-social-sciences/subjects/department-of-social-sciences/education-sciences-and-psychology/institute/).
          
          - 
          
          - Big fan of **#rstats**.

    socialIcons:
        - name: linkedin
          url: "https://www.linkedin.com/in/lennart-klein/"
        - name: twitter
          url: "https://twitter.com/lennartkl3in"
        - name: github
          url: "https://github.com/kleinlennart"
        


    analytics:
        google:
            SiteVerificationTag: "XYZabc"

    cover:
        hidden: true # hide everywhere but not in structured data
        hiddenInList: true # hide on list pages and home
        hiddenInSingle: true # hide on single page

    # for search
    # https://fusejs.io/api/options.html
    fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        keys: ["title", "permalink", "summary", "content"]

## ??
# taxonomies:
#     category: categories
#     tag: tags
#     series: series

# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
# pygmentsUseClasses: true
# markup:
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         style: monokai
