# -> https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs
# Example: https://github.com/adityatelange/hugo-PaperMod/blob/exampleSite/config.yml
# https://github.com/adityatelange/hugo-PaperMod/wiki/Installation#sample-configyml

theme: "hugo-PaperMod"
baseURL: "https://www.kleinbutsignificant.com/"
publishDir: "public" # directory under which to generate the website.
languageCode: en-us
title: "@kleinbutsignificant"

enableEmoji: true # use Emojis like :smile: in Markdown
ignoreFiles:
  [
    "\\.Rmd$",
    "\\.Rmarkdown$",
    "_cache$",
    "(^|/)renv$",
    "renv\\.lock$",
    "\\.qmd$",
    "\\.ipynb$",
    "\\.py$",
  ]
# [permalinks]
# uglyURLs

paginate: 5
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: G-GC2LB6CKDN

## Can result in weird JSON parsing errors
minify:
  disableXML: true
  # minifyOutput: true

menu:
  main:
    - identifier: about
      name: "About"
      url: /about/
      weight: 1
    - identifier: cv
      name: "CV"
      url: /vitae/
      weight: 2
    - identifier: blog
      name: "Blog"
      url: /archives/
      weight: 3
    - identifier: pubs
      name: "Publications"
      url: /pubs/
      weight: 4
    - identifier: projects
      name: "Projects"
      url: /projects/
      weight: 5
    - identifier: categories
      name: "Topics"
      url: /categories/
      weight: 6
    - identifier: tags
      name: "Tags"
      url: /tags/
      weight: 7
    - identifier: slides
      name: "Slides"
      url: /slides/
      weight: 8
    - identifier: art
      name: "Art"
      url: /art/
      weight: 9
    - identifier: search
      name: "🔍"
      url: /search/
      weight: 10

# For search
outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary

params:
  mainSections:
    - post # https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#posts-from-only-one-foldersection-visible-on-home-page
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: "@kleinbutsignificant" # <meta property="og:site_name" content="<title>"/>
  description: "Blog of Lennart Klein about Data Science, Politics, and Productivity"
  author: "Lennart Klein"
  keywords: [Blog, Data Science, Academia]
  images: ["<link or path of image for opengraph, twitter-cards>"] # FIXME
  # DateFormat: "January 2, 2006"

  defaultTheme: light # dark, light
  disableThemeToggle: true

  ShowReadingTime: false
  ShowShareButtons: false
  disableSpecial1stPost: false
  comments: false # https://github.com/adityatelange/hugo-PaperMod/wiki/Features#comments
  hideSummary: false
  hidemeta: false
  showtoc: false
  tocopen: false
  ShowPostNavLinks: false
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: false
  ShowRssButtonInSectionTermList: false
  UseHugoToc: true
  # disableScrollToTop: true

  assets:
    # https://favicon.io/
    # /static folder
    disableHLJS: true # to disable highlight.js
    # doesn't seem to do anything
    
    disableFingerprinting: true
    favicon: "favicon16.png"
    favicon16x16: "favicon16.png"
    favicon32x32: "<link / abs url>"
    apple_touch_icon: "<link / abs url>"
    safari_pinned_tab: "<link / abs url>"

  label:
    text: "@kleinbutsignificant" # Header
    # icon: /apple-touch-icon.png
    iconHeight: 35

  # profile-mode
  # profileMode:
  #     enabled: false
  #     title: "Title" # optional default will be site title
  #     subtitle: "This is subtitle"
  #     imageUrl: "static/profile_round.png" # optional
  #     imageTitle: "<title of image as alt>" # optional
  #     imageWidth: 120 # custom size
  #     imageHeight: 120 # custom size
  #     buttons:
  #         - name: Archive
  #           url: "/archive"
  #         - name: Github
  #           url: "https://github.com/"

  # home-info mode
  homeInfoParams:
    # custom params from profileMode and inserted in home_info.html partial
    imageUrl: profile_round.png
    imageWidth: 200
    imageHeight: 200
    # default homeInfoParams:
    Title: "Hi, I'm Lennart \U0001F44B"
    Content: >
      - 👨🏼‍🎓 I'm an **Undergraduate Student** of **Political Science**, **Sociology**, and <br>
      **Psychology** at the [University of Tübingen](https://uni-tuebingen.de/en/) 

      - 👨🏼‍💻 I work as a **Research** and **Teaching Assistant** at the [Hector Research Institute](https://uni-tuebingen.de/en/faculties/faculty-of-economics-and-social-sciences/subjects/department-of-social-sciences/education-sciences-and-psychology/institute/)

      - 🌱 I'm also a **Research Volunteer** at the [Social Change Lab](https://www.socialchangelab.org/)


      - <br> Big fan of [**#rstats**](https://www.r-project.org/).

  # - I write about Data Science, Politics and Productivity.
  # independent of page mode
  socialIcons:
    - name: linkedin
      title: "LinkedIn"
      url: "https://www.linkedin.com/in/lennart-klein/"
    - name: twitter
      title: "Whatever"
      url: "https://twitter.com/kleinbutfiner"
    - name: github
      title: "GitHub"
      url: "https://github.com/kleinlennart"
    - name: googlescholar
      title: "Google Scholar"
      url: "https://scholar.google.com/citations?hl=en&user=vK0kK7UAAAAJ"
    # - name: Email
      # title: "Mail"
      # url: "mailto:"
      # NOTE: set in social_icons.html

  # analytics:
  #   google:
  #     SiteVerificationTag: "G-GC2LB6CKDN"

  cover:
    hidden: false # hide everywhere but not in structured data
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: true # hide on single page

  editPost:
    URL: "https://github.com/kleinlennart/kleinbutsignificant.com/edit/master/content"
    Text: "🖊" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

## ??
# taxonomies:
#     category: categories
#     tag: tags
#     series: series

# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
# https://github.com/rstudio/blogdown/issues/360

# before set disableHLJS: true

# makes everything go white for some reason
pygmentsUseClasses: false 
markup:
  # allow raw HTML (as many R and Python packages will produce computational output using raw HTML rather than markdown)
  goldmark:
    renderer:
      unsafe: true
    # highlight:
    #   anchorLineNos: false
    #   lineNos: false
    #   lineNoStart: 1
    #   lineAnchors: ""
    #   codeFences: true
    #   guessSyntax: false
    #   hl_Lines: ""
    #   hl_inline: false
    #   lineNumbersInTable: true
    #   noClasses: true
    #   noHl: false
    #   style: monokailight
    #   tabWidth: 4
    # style: github # https://xyproto.github.io/splash/docs/all.html
